CREATE DATABASE IF NOT EXISTS projetobase;

USE projetobase;

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    status CHAR(1) NOT NULL,
    permissao VARCHAR(255) NOT NULL,
    dh_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dh_atualizado TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    dh_excluido TIMESTAMP NULL DEFAULT NULL
);